import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/widgets/Footer/ui/Footer";
import { Header } from "@/widgets/Header/ui/Header";
import { PageTransitionProvider } from "./providers/PageTransitionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PageTransitionProvider>
          <Header />
            {children}
          <Footer />
        </PageTransitionProvider>
      </body>
    </html>
  );
}
